version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.8 
    steps: 
      - checkout 
      - run: make tests

workflows:
  version: 2
  build-workflow:
  jobs:
    - build
                                      
                                      
                                      
