version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/anekkanti/toutloop
    steps: 
      - checkout 
      - run: 
        command: | 
          make tests
          go tool cover -html=cover.out -o coverage.html 
          mkdir -p /tmp/artifacts
          mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: cover.out

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
                                      
                                      
                                      
