version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/anekkanti/toutloop
    steps: 
      - checkout 
      - run: make tests

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
                                      
                                      
                                      
